# https://docs.travis-ci.com/user/languages/android
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23
#Only CI for master & dev
branches:
  only:
    - master
    - dev

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/